#!/usr/bin/env python

import sys
import json

from ratnav.daemon import Daemon
from ratnav.app import RatNavApp

import cv2.cv as cv

try:
    config = json.load(open("/etc/ratnav/config.json"))
except IOError:
    config = json.load(open("../etc/ratnav/config.json"))
finally:
    pass  # TODO: Hmm, maybe better bail out?


def log(f, *what):
    for item in what:
        f.write(str(item))


class MyDaemon(Daemon):
    def run(self):
        f = open('/tmp/logga', 'w')
        log(f, "Trying to open camera")
        capture = cv.CaptureFromCAM(0)
        log(f, "Camera opened")
        frame = cv.QueryFrame(capture)  # Take a frame to init buffer sizes
        log(f, "First frame taken: ", type(frame), frame)

        gray_frame = cv.CreateImage(cv.GetSize(frame), cv.IPL_DEPTH_8U, 1)
        average_frame = cv.CreateImage(cv.GetSize(frame), cv.IPL_DEPTH_32F, 3)
        f.close()
        ratnavapp = RatNavApp(show_windows=False, do_audio=True)
        ratnavapp.run()


if __name__ == "__main__":
    daemon = MyDaemon('/var/run/ratnav.pid',
                      stdout='/tmp/ratnav.out',
                      stderr='/tmp/ratnav.err',
                      user='ratnav',
                      group='ratnav')

    if len(sys.argv) >= 2:
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        else:
            print("Unknown command")
            sys.exit(2)
        sys.exit(0)
    else:
        print(sys.argv)
        print("usage: %s start|stop|restart" % sys.argv[0])
        sys.exit(2)
